version: "3.9"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - ../db:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=domain
      - POSTGRES_USER=domain
      - POSTGRES_PASSWORD=domain
    ports:
      - "5432:5432"

#  web_actix:
#    image: backend-image-py-and-rust:dev
#    working_dir: /code/actix_backend
#    command: cargo-watch -x run
#    volumes:
#      - .:/code
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env
#    depends_on:
#      - db

  web_django:
    image: backend-image-py-and-rust:dev
    build: .
    working_dir: /code/config
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ../logs:/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

